language: php
php:
  - '5.4'
  - '5.6'
  - '7.0'
  - hhvm # on Trusty only
  - nightly

services:
  - mysql

before_script:
  - sudo apt-get update
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  - sudo apt-get install php5-fpm
  # enable php-fpm
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - sudo sed -i -e "s,www-data,travis,g" /etc/apache2/envvars
  - sudo chown -R travis:travis /var/lib/apache2/fastcgi
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  # configure apache virtual hosts
  - sudo cp -f build/travis-ci-apache.txt /etc/apache2/sites-available/000-default.conf
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/000-default.conf
  - sudo service apache2 restart
  #website setup steps
  - cp ./example_config.ini ./web/config.ini
  - sed -i -e "s,\"username\",\"travis\",g" ./web/config.ini
  - sed -i -e "s,\"password\",\"\",g" ./web/config.ini
  - sed -i -e "s,\"host_or_ip\",\"127.0.0.1\",g" ./web/config.ini
  - sed -i -e "s,location_here,,g" ./web/config.ini
  - cat ./web/config.ini
  - mysql -e 'CREATE DATABASE db_name;'
  - mysql db_name < ./web/setup/skeleton.sql

after_success:
  - bash <(curl -s https://codecov.io/bash)