language: php

matrix:
  include:
    - php: '5.4'
    - php: '5.6'
    - php: '7.0'
    - php: hhvm
      sudo: required
    - php: nightly
  allow_failures:
    - php: hhvm

services:
  - mysql

before_script:
  #check for php errors
  - '! find ./web -type f -name "*.php" ! -path "./web/include/fpdf16/tutorial*" -exec php -d error_reporting=32767 -l {} \; 2>&1 >&- | grep "^"'
  #workaround for hhvm and phpunit
  - curl -sSLf -o ~/.phpenv/versions/hhvm/bin/phpunit https://phar.phpunit.de/phpunit-5.7.phar
  #website setup steps
  - cp ./example_config.ini ./web/config.ini
  - sed -i -e "s,\"username\",\"travis\",g" ./web/config.ini
  - sed -i -e "s,\"password\",\"\",g" ./web/config.ini
  - sed -i -e "s,\"host_or_ip\",\"127.0.0.1\",g" ./web/config.ini
  - sed -i -e "s,location_here,,g" ./web/config.ini
  - mysql -e 'CREATE DATABASE db_name;'
  - mysql db_name < ./skeleton.sql

script:
  - phpunit unit_tests/indexText.php
  - bash <(curl -s https://codecov.io/bash)
