language: php

matrix:
  include:
    - php: '5.4'
    - php: '5.6'
    - php: '7.0'
    - php: hhvm
      sudo: required
    - php: nightly
  allow_failures:
    - php: hhvm

services:
  - mysql

before_script:
  #workaround for hhvm and phpunit
  - curl -sSLf -o ~/.phpenv/versions/hhvm/bin/phpunit https://phar.phpunit.de/phpunit-5.7.phar
  #website setup steps
  - cp ./example_config.ini ./web/config.ini
  - sed -i -e "s,\"username\",\"travis\",g" ./web/config.ini
  - sed -i -e "s,\"password\",\"\",g" ./web/config.ini
  - sed -i -e "s,\"host_or_ip\",\"127.0.0.1\",g" ./web/config.ini
  - sed -i -e "s,location_here,,g" ./web/config.ini
  - cat ./web/config.ini
  - pwd
  - ls -la `pwd`
  - ls -la ./web
  - mysql -e 'CREATE DATABASE db_name;'
  - mysql db_name < ./skeleton.sql

after_success:
  - bash <(curl -s https://codecov.io/bash)